"""A small demo catalog with deliberately overlapping tools."""
from toolmem import Tool

CATALOG = [
    Tool("get_weather_forecast", "Get the weather forecast for a city for the next days.",
         {"type": "object", "properties": {"city": {"type": "string"}, "days": {"type": "integer"}}}, tags=["weather"]),
    Tool("get_current_weather", "Get current temperature and conditions for a city.",
         {"type": "object", "properties": {"city": {"type": "string"}}}, tags=["weather"]),
    Tool("send_email", "Send an email to a recipient.",
         {"type": "object", "properties": {"to": {"type": "string"}, "subject": {"type": "string"}, "body": {"type": "string"}}}, tags=["comms"]),
    Tool("send_slack_message", "Post a message to a Slack channel.",
         {"type": "object", "properties": {"channel": {"type": "string"}, "text": {"type": "string"}}}, tags=["comms"]),
    Tool("search_web", "Search the web and return result snippets.",
         {"type": "object", "properties": {"query": {"type": "string"}}}, tags=["research"]),
    Tool("search_arxiv", "Search arXiv for academic papers.",
         {"type": "object", "properties": {"query": {"type": "string"}}}, tags=["research"]),
    Tool("convert_currency", "Convert an amount between currencies.",
         {"type": "object", "properties": {"amount": {"type": "number"}, "from_ccy": {"type": "string"}, "to_ccy": {"type": "string"}}}, tags=["finance"]),
    Tool("get_stock_price", "Get the latest stock price for a ticker.",
         {"type": "object", "properties": {"ticker": {"type": "string"}}}, tags=["finance"]),
    Tool("create_calendar_event", "Create an event on the user's calendar.",
         {"type": "object", "properties": {"title": {"type": "string"}, "start": {"type": "string"}}}, tags=["calendar"]),
    Tool("list_calendar_events", "List upcoming calendar events.",
         {"type": "object", "properties": {"days": {"type": "integer"}}}, tags=["calendar"]),
    Tool("get_current_time", "Return the current date and time in a timezone.",
         {"type": "object", "properties": {"timezone": {"type": "string"}}}, tags=["utility"]),
    Tool("run_sql_query", "Run a read-only SQL query against the analytics database.",
         {"type": "object", "properties": {"sql": {"type": "string"}}}, tags=["data"]),
    Tool("create_github_issue", "Open a new issue in a GitHub repository.",
         {"type": "object", "properties": {"repo": {"type": "string"}, "title": {"type": "string"}}}, tags=["dev"]),
    Tool("translate_text", "Translate text into a target language.",
         {"type": "object", "properties": {"text": {"type": "string"}, "target_language": {"type": "string"}}}, tags=["utility"]),
    Tool("book_flight", "Book a flight between two airports on a date.",
         {"type": "object", "properties": {"origin": {"type": "string"}, "destination": {"type": "string"}, "date": {"type": "string"}}}, tags=["travel"]),
]

# Queries phrased the way users talk, often without the tool's own words.
CASES = [
    ("will it rain in London this weekend", ["get_weather_forecast"]),
    ("how hot is it in Delhi right now", ["get_current_weather"]),
    ("email my manager the report", ["send_email"]),
    ("ping the #eng channel that the deploy is done", ["send_slack_message"]),
    ("find recent papers on agent memory", ["search_arxiv"]),
    ("look up who won the match yesterday", ["search_web"]),
    ("how many rupees is 50 dollars", ["convert_currency"]),
    ("what is NVDA trading at", ["get_stock_price"]),
    ("schedule a meeting with Priya tomorrow at 3", ["create_calendar_event"]),
    ("what's on my agenda this week", ["list_calendar_events"]),
    ("what time is it in Tokyo", ["get_current_time"]),
    ("how many signups did we get last month in the database", ["run_sql_query"]),
    ("file a bug in our repo about the login crash", ["create_github_issue"]),
    ("say this in Hindi", ["translate_text"]),
    ("get me a plane ticket from Delhi to Mumbai on Friday", ["book_flight"]),
]
